select * from customer 

--  what is total revenue generated by male vs femle customers
select gender, SUM(purchase_amount) from customer GROUP BY gender


-- which customer used a discont but still spent more than average purchase eamount
SELECT customer_id, purchase_amount from customer where discount_applied='yes' and purchase_amount > (select AVG(purchase_amount) from customer)


-- which are the top 5 products with highest average review rating 
select top 5 item_purchased, round(AVG(review_rating),2) from customer 
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC

-- compare the avg purchase amount between starndard and express shipping
SELECT shipping_type, AVG(purchase_amount) from customer 
where shipping_type IN ('Express','Standard') 
GROUP BY shipping_type

-- do subscribed customeers spend more? compare avg spend and total revenue b/w subscribers and non subscribers
select subscription_status, 
        COUNT(customer_id) as total_customers, 
        SUM(purchase_amount) as total_revenue, 
        AVG(purchase_amount) as average_spend
from customer  
GROUP BY subscription_status
ORDER BY total_revenue,average_spend DESC

-- WHICH 5 PRODUCTS HAS THE HIGHEST PERCENTAGE OF PURCHAGES WITH DISCOUNT APPLIED
SELECT top 5 item_purchased, 
        100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) as discount_rate
from customer  
GROUP BY item_purchased  
ORDER BY discount_rate DESC

--  segment customers into new returning and loyal based on their total number of previous purchacse and show the count of each segment
with customer_type as (
        select customer_id, previous_purchases,
        CASE 
                WHEN previous_purchases = 1 THEN 'New'
                WHEN previous_purchases  BETWEEN 2 AND 10 THEN 'Returning'
                ELSE 'Loyal'
        END
        as customer_segment
        from customer
)
select customer_segment,count(*) as "number_of_customers"
from customer_type
GROUP BY customer_segment;


-- what are the top 3 most purchased products in each category

with item_counts as (
select category, 
        item_purchased, 
        COUNT(customer_id) as total_orders,
        ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) desc) as item_rank
from customer 
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders 
from item_counts
where item_rank<=3;

-- are customers repeated buyers   (more then 5 previous purchases)     also likely to subscribe
select subscription_status,
count(customer_id) as repeated_buyers
from customer
where previous_purchases >5
group by subscription_status;

-- what is revenue contribution of eact age group
select age_group, sum(purchase_amount) as total_revenue
from customer
GROUP BY age_group
ORDER BY total_revenue desc;


select top 5 * from customer;

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = N'customer';